### ISSUE TITLE
Regression causing the importation of .db chat files to fail

### ISSUE THREAD

**Issue by gsquarediv** [Jeffser/Alpaca#1049]
**Describe the bug**

After updating from version 8.1.1 to 8.3.1, imported .db chat files no longer appear in the sidebar until the application is restarted.

**Expected behavior**

I expect imported chats to appear in the sidebar without restarting Alpaca.

**Debugging information**

```
INFO    [main.py | main] Alpaca version: 8.3.1
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:981: FINISHME: support more multi-planar formats with DRM modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:949: FINISHME: support YUV colorspace with DRM format modifiers
('202511220605018533692747184b63864c3392f2cf9dd200ccce', 'Plasma Explained 💡', None, 0)
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/widgets/dialog.py", line 351, in <lambda>
    lambda file_dialog, result: callback(__open_finish_wrapper(file_dialog, result)) if result else None
                                ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 412, in on_chat_imported
    self.get_chat_list_page().add_chat(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        chat_name=chat[1],
        ^^^^^^^^^^^^^^^^^^
        chat_id=chat[0],
        ^^^^^^^^^^^^^^^^
        mode=1
        ^^^^^^
    )
    ^
TypeError: ChatList.add_chat() missing 1 required positional argument: 'is_template'
```

**Comment by Jeffser** [comment]
hi, thanks for the report, I just fixed it!

https://github.com/Jeffser/Alpaca/commit/ccaa6859416879ae00c67cc1cc19b3c7eb1227cc
