### ISSUE TITLE
Alpaca is inoperable after update to 5.3.0

### ISSUE THREAD

**Issue by gmoore-sjcorg** [Jeffser/Alpaca#626]
**Describe the bug**
App opens but unable to start a chat and no models are loaded.

**Expected behavior**
App to open and allow creation of new chats.

**Screenshots**

![Image](https://github.com/user-attachments/assets/57551d59-efe3-4f91-8a92-add3e2625634)

**Debugging information**
```
INFO    [main.py | main] Alpaca version: 5.3.0                                                                                      
Traceback (most recent call last):                                                                                                  
  File "/app/share/Alpaca/alpaca/main.py", line 125, in do_activate                                                                 
    win = AlpacaWindow(application=self)                                                                                            
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            
  File "/app/share/Alpaca/alpaca/window.py", line 1157, in __init__                                                                 
    self.model_manager_stack.set_enable_transitions(True)                                                                           
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                 
AttributeError: 'ViewStack' object has no attribute 'set_enable_transitions'                                                        
Traceback (most recent call last):                                                                                                  
  File "/app/share/Alpaca/alpaca/window.py", line 557, in message_search_changed                                                    
    current_chat = self.chat_list_box.get_current_chat()                                                                            
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                              
AttributeError: 'NoneType' object has no attribute 'get_current_chat'
```

**Comment by LogExE** [comment]
same on Fedora 41

**Comment by Jeffser** [comment]
Please update the app, there was a mistake when building the Flatpak, you see, Alpaca now requires the Gnome 48 runtime but I didn't change it by mistake when publishing the app to Flathub, the fix is already out

**Comment by gmoore-sjcorg** [comment]
After the update it is functioning again, Thank you @Jeffser
